server:
  port: 9090

spring:
  application:
    name: TICKET-BOOKING-SERVICE
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_booking_system
    username: root
    password: root
    hikari:
      connection-timeout: 20000 
      minimum-idle: 10 
      maximum-pool-size: 30 
      idle-timeout: 10000 
      max-lifetime: 1000 
      auto-commit: true