/*
 * Created on 2022-02-23 ( 12:58:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Booking"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="booking", catalog="ticket_booking_system" )
public class Booking implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="shows_id")
    private Integer    showsId ;

    @Column(name="number_of_seats")
    private Integer    numberOfSeats ;

    @Column(name="status", length=32)
    private String     status ;

    @Column(name="total_amount")
    private Double     totalAmount ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time")
    private Date       createdTime ;

    @Column(name="updated_by")
    private Integer    updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time")
    private Date       updatedTime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="booking")
    private List<ShowsSeats> listOfShowsSeats ; 

    @ManyToOne
    @JoinColumn(name="shows_id", referencedColumnName="id", insertable=false, updatable=false)
    private Shows      shows ; 

    @OneToMany(mappedBy="booking")
    private List<Payment> listOfPayment ; 


    /**
     * Constructor
     */
    public Booking() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setShowsId( Integer showsId ) {
        this.showsId = showsId ;
    }
    public Integer getShowsId() {
        return this.showsId;
    }

    public void setNumberOfSeats( Integer numberOfSeats ) {
        this.numberOfSeats = numberOfSeats ;
    }
    public Integer getNumberOfSeats() {
        return this.numberOfSeats;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    public void setTotalAmount( Double totalAmount ) {
        this.totalAmount = totalAmount ;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedTime( Date createdTime ) {
        this.createdTime = createdTime ;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy ;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedTime( Date updatedTime ) {
        this.updatedTime = updatedTime ;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    //--- GETTERS FOR LINKS
    public List<ShowsSeats> getListOfShowsSeats() {
        return this.listOfShowsSeats;
    } 

    public Shows getShows() {
        return this.shows;
    } 

    public List<Payment> getListOfPayment() {
        return this.listOfPayment;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(showsId);
        sb.append("|");
        sb.append(numberOfSeats);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(totalAmount);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdTime);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedTime);
        return sb.toString(); 
    } 

}
