/*
 * Created on 2022-02-23 ( 12:58:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPA entity class for "City"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "city", catalog = "ticket_booking_system")
public class City implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", nullable = false)
	private Integer id;

	@Column(name = "name", length = 200)
	private String name;

	@Column(name = "code", length = 200)
	private String code;

	@Column(name = "pincode")
	private Integer pincode;

	// --- ENTITY LINKS ( RELATIONSHIP )
	@ManyToOne
	@JoinColumn(name = "state_id", referencedColumnName = "id", insertable = false, updatable = false)
	private State state;

	@OneToMany(mappedBy = "city")
	private List<Theatre> theatreList;

	/**
	 * Constructor
	 */
	public City() {
		super();
	}

	// --- GETTERS & SETTERS FOR FIELDS
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCode() {
		return this.code;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

	public Integer getPincode() {
		return this.pincode;
	}

	// --- GETTERS FOR LINKS
	public State getState() {
		return this.state;
	}

	public List<Theatre> getListOfTheatre() {
		return this.theatreList;
	}

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(id);
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(code);
		sb.append("|");
		sb.append(pincode);
		return sb.toString();
	}

}
