/*
 * Created on 2022-02-23 ( 12:58:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Movie"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="movie", catalog="ticket_booking_system" )
public class Movie implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=400)
    private String     name ;

    @Column(name="about", length=800)
    private String     about ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="release_date", nullable=false)
    private Date       releaseDate ;

    @Column(name="duration")
    private Integer    duration ;

    @Column(name="genres", length=200)
    private String     genres ;

    @Column(name="cast", length=200)
    private String     cast ;

    @Column(name="crew", length=200)
    private String     crew ;

    @Column(name="language", length=200)
    private String     language ;

    @Column(name="certificate", length=5)
    private String     certificate ;

    @Column(name="image_url", length=200)
    private String     imageUrl ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false)
    private Date       createdTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false)
    private Date       updatedTime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="movie")
    private List<Shows> listOfShows ; 


    /**
     * Constructor
     */
    public Movie() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setAbout( String about ) {
        this.about = about ;
    }
    public String getAbout() {
        return this.about;
    }

    public void setReleaseDate( Date releaseDate ) {
        this.releaseDate = releaseDate ;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }

    public void setDuration( Integer duration ) {
        this.duration = duration ;
    }
    public Integer getDuration() {
        return this.duration;
    }

    public void setGenres( String genres ) {
        this.genres = genres ;
    }
    public String getGenres() {
        return this.genres;
    }

    public void setCast( String cast ) {
        this.cast = cast ;
    }
    public String getCast() {
        return this.cast;
    }

    public void setCrew( String crew ) {
        this.crew = crew ;
    }
    public String getCrew() {
        return this.crew;
    }

    public void setLanguage( String language ) {
        this.language = language ;
    }
    public String getLanguage() {
        return this.language;
    }

    public void setCertificate( String certificate ) {
        this.certificate = certificate ;
    }
    public String getCertificate() {
        return this.certificate;
    }

    public void setImageUrl( String imageUrl ) {
        this.imageUrl = imageUrl ;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setCreatedTime( Date createdTime ) {
        this.createdTime = createdTime ;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setUpdatedTime( Date updatedTime ) {
        this.updatedTime = updatedTime ;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    //--- GETTERS FOR LINKS
    public List<Shows> getListOfShows() {
        return this.listOfShows;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(about);
        sb.append("|");
        sb.append(releaseDate);
        sb.append("|");
        sb.append(duration);
        sb.append("|");
        sb.append(genres);
        sb.append("|");
        sb.append(cast);
        sb.append("|");
        sb.append(crew);
        sb.append("|");
        sb.append(language);
        sb.append("|");
        sb.append(certificate);
        sb.append("|");
        sb.append(imageUrl);
        sb.append("|");
        sb.append(createdTime);
        sb.append("|");
        sb.append(updatedTime);
        return sb.toString(); 
    } 

}
