/*
 * Created on 2022-02-23 ( 12:58:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Payment"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="payment", catalog="ticket_booking_system" )
public class Payment implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="booking_id")
    private Integer    bookingId ;

    @Column(name="amount")
    private Double     amount ;

    @Column(name="discount_coupon", length=100)
    private String     discountCoupon ;

    @Column(name="transaction_id")
    private Integer    transactionId ;

    @Column(name="payment_gateway_id")
    private Integer    paymentGatewayId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="booking_id", referencedColumnName="id", insertable=false, updatable=false)
    private Booking    booking ; 


    /**
     * Constructor
     */
    public Payment() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setBookingId( Integer bookingId ) {
        this.bookingId = bookingId ;
    }
    public Integer getBookingId() {
        return this.bookingId;
    }

    public void setAmount( Double amount ) {
        this.amount = amount ;
    }
    public Double getAmount() {
        return this.amount;
    }

    public void setDiscountCoupon( String discountCoupon ) {
        this.discountCoupon = discountCoupon ;
    }
    public String getDiscountCoupon() {
        return this.discountCoupon;
    }

    public void setTransactionId( Integer transactionId ) {
        this.transactionId = transactionId ;
    }
    public Integer getTransactionId() {
        return this.transactionId;
    }

    public void setPaymentGatewayId( Integer paymentGatewayId ) {
        this.paymentGatewayId = paymentGatewayId ;
    }
    public Integer getPaymentGatewayId() {
        return this.paymentGatewayId;
    }

    //--- GETTERS FOR LINKS
    public Booking getBooking() {
        return this.booking;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(bookingId);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(discountCoupon);
        sb.append("|");
        sb.append(transactionId);
        sb.append("|");
        sb.append(paymentGatewayId);
        return sb.toString(); 
    } 

}
