/*
 * Created on 2022-02-23 ( 12:58:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Role"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="role", catalog="ticket_booking_system" )
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="role", length=100)
    private String     role ;

    @Column(name="code", length=100)
    private String     code ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="role")
    private List<User> listOfUser ; 


    /**
     * Constructor
     */
    public Role() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setRole( String role ) {
        this.role = role ;
    }
    public String getRole() {
        return this.role;
    }

    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    //--- GETTERS FOR LINKS
    public List<User> getListOfUser() {
        return this.listOfUser;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(role);
        sb.append("|");
        sb.append(code);
        return sb.toString(); 
    } 

}
