/*
 * Created on 2022-02-23 ( 12:58:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JPA entity class for "ScreenSeats"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "screen_seats", catalog = "ticket_booking_system")
public class ScreenSeats implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", nullable = false)
	private Integer id;

	// --- ENTITY DATA FIELDS
	@Column(name = "name", length = 50)
	private String name;

	@Column(name = "screen_id")
	private Integer screenId;

	@Column(name = "type", length = 40)
	private String type;

	@Column(name = "price")
	private Double price;

	// --- ENTITY LINKS ( RELATIONSHIP )
	@ManyToOne
	@JoinColumn(name = "screen_id", referencedColumnName = "id", insertable = false, updatable = false)
	private Screen screen;

	@OneToMany(mappedBy = "screenSeats")
	private List<ShowsSeats> listOfShowsSeats;

	/**
	 * Constructor
	 */
	public ScreenSeats() {
		super();
	}

	// --- GETTERS & SETTERS FOR FIELDS
	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public void setScreenId(Integer screenId) {
		this.screenId = screenId;
	}

	public Integer getScreenId() {
		return this.screenId;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getPrice() {
		return this.price;
	}

	// --- GETTERS FOR LINKS
	public Screen getScreen() {
		return this.screen;
	}

	public List<ShowsSeats> getListOfShowsSeats() {
		return this.listOfShowsSeats;
	}

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(id);
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(screenId);
		sb.append("|");
		sb.append(type);
		sb.append("|");
		sb.append(price);
		return sb.toString();
	}

}
