/*
 * Created on 2022-02-23 ( 12:58:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "ShowsSeats"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="shows_seats", catalog="ticket_booking_system" )
public class ShowsSeats implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="booking_id")
    private Integer    bookingId ;

    @Column(name="screen_seat_id")
    private Integer    screenSeatId ;

    @Column(name="shows_id")
    private Integer    showsId ;

    @Column(name="status", length=10)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="booking_id", referencedColumnName="id", insertable=false, updatable=false)
    private Booking    booking ; 

    @ManyToOne
    @JoinColumn(name="shows_id", referencedColumnName="id", insertable=false, updatable=false)
    private Shows      shows ; 

    @ManyToOne
    @JoinColumn(name="screen_seat_id", referencedColumnName="id", insertable=false, updatable=false)
    private ScreenSeats screenSeats ; 


    /**
     * Constructor
     */
    public ShowsSeats() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setBookingId( Integer bookingId ) {
        this.bookingId = bookingId ;
    }
    public Integer getBookingId() {
        return this.bookingId;
    }

    public void setScreenSeatId( Integer screenSeatId ) {
        this.screenSeatId = screenSeatId ;
    }
    public Integer getScreenSeatId() {
        return this.screenSeatId;
    }

    public void setShowsId( Integer showsId ) {
        this.showsId = showsId ;
    }
    public Integer getShowsId() {
        return this.showsId;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    //--- GETTERS FOR LINKS
    public Booking getBooking() {
        return this.booking;
    } 

    public Shows getShows() {
        return this.shows;
    } 

    public ScreenSeats getScreenSeats() {
        return this.screenSeats;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(bookingId);
        sb.append("|");
        sb.append(screenSeatId);
        sb.append("|");
        sb.append(showsId);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
