/*
 * Created on 2022-02-23 ( 12:58:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.ticket.booking.demo.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "User"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="user", catalog="ticket_booking_system" )
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="role_id")
    private Integer    roleId ;

    @Column(name="username", length=200)
    private String     username ;

    @Column(name="password", length=200)
    private String     password ;

    @Column(name="display_name", length=200)
    private String     displayName ;

    @Column(name="email_id", length=60)
    private String     emailId ;

    @Column(name="country_code", length=5)
    private String     countryCode ;

    @Column(name="mobile", length=10)
    private String     mobile ;

    @Column(name="mfa")
    private Boolean    mfa ;

    @Column(name="is_active")
    private Boolean    isActive ;

    @Column(name="is_locked")
    private Boolean    isLocked ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", nullable=false)
    private Date       createdTime ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_time", nullable=false)
    private Date       updatedTime ;

    @Column(name="updated_by")
    private Integer    updatedBy ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="role_id", referencedColumnName="id", insertable=false, updatable=false)
    private Role       role ; 

    @OneToMany(mappedBy="user")
    private List<Theatre> listOfTheatre ; 


    /**
     * Constructor
     */
    public User() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setRoleId( Integer roleId ) {
        this.roleId = roleId ;
    }
    public Integer getRoleId() {
        return this.roleId;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPassword( String password ) {
        this.password = password ;
    }
    public String getPassword() {
        return this.password;
    }

    public void setDisplayName( String displayName ) {
        this.displayName = displayName ;
    }
    public String getDisplayName() {
        return this.displayName;
    }

    public void setEmailId( String emailId ) {
        this.emailId = emailId ;
    }
    public String getEmailId() {
        return this.emailId;
    }

    public void setCountryCode( String countryCode ) {
        this.countryCode = countryCode ;
    }
    public String getCountryCode() {
        return this.countryCode;
    }

    public void setMobile( String mobile ) {
        this.mobile = mobile ;
    }
    public String getMobile() {
        return this.mobile;
    }

    public void setMfa( Boolean mfa ) {
        this.mfa = mfa ;
    }
    public Boolean getMfa() {
        return this.mfa;
    }

    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive ;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }

    public void setIsLocked( Boolean isLocked ) {
        this.isLocked = isLocked ;
    }
    public Boolean getIsLocked() {
        return this.isLocked;
    }

    public void setCreatedTime( Date createdTime ) {
        this.createdTime = createdTime ;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setUpdatedTime( Date updatedTime ) {
        this.updatedTime = updatedTime ;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedBy( Integer updatedBy ) {
        this.updatedBy = updatedBy ;
    }
    public Integer getUpdatedBy() {
        return this.updatedBy;
    }

    //--- GETTERS FOR LINKS
    public Role getRole() {
        return this.role;
    } 

    public List<Theatre> getListOfTheatre() {
        return this.listOfTheatre;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(roleId);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(displayName);
        sb.append("|");
        sb.append(emailId);
        sb.append("|");
        sb.append(countryCode);
        sb.append("|");
        sb.append(mobile);
        sb.append("|");
        sb.append(mfa);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(isLocked);
        sb.append("|");
        sb.append(createdTime);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(updatedTime);
        sb.append("|");
        sb.append(updatedBy);
        return sb.toString(); 
    } 

}
